apiVersion: v1
kind: Service
metadata:
  name: toy-robot
  labels:
    app: toy-robot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
  selector:
    app: toy-robot